image: amazoncorretto:17.0.7

variables:
  BRANCH_NAME: $CI_COMMIT_REF_NAME
  BUILD_NUMBER: $CI_PIPELINE_ID

stages:
  - test
  - release
  - gitlab-release

test:
  stage: test
  script:
    - ./gradlew --stacktrace --info --warning-mode all :spring-bootstrap:test -Dfile.encoding=UTF8
  artifacts:
    reports:
      junit: modules/**/build/test-results/test/TEST-*.xml

release:
  stage: release
  only:
    - /^release\/.*$/
  script:
    - ESCAPED_BRANCH_NAME="$(echo "$BRANCH_NAME" | sed -e 's|release/||g' |  sed -e 's|/|_|g' )"
    - ./gradlew --info :spring-bootstrap:buildPlugin :spring-bootstrap:signPlugin :spring-bootstrap:publishPlugin -PsnapshotVersion=$BUILD_NUMBER -PdistFilePostfix=$ESCAPED_BRANCH_NAME-b$BUILD_NUMBER -PsetUntilVersion -Pobfuscate
    - ./gradlew :spring-bootstrap:runPluginVerifier
  artifacts:
    paths:
      - modules/spring-bootstrap/build/reports/pluginVerifier
      - modules/spring-bootstrap/build/distributions/*.zip
      - modules/spring-bootstrap/build/distributions/source.map

release_job:
  stage: gitlab-release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: release
      artifacts: true
  only:
    - /^release\/.*$/
  script:
    - echo "running release_job"
  release:
    tag_name: release/$ESCAPED_BRANCH_NAME-b$BUILD_NUMBER
    description: 'Release created using the release-cli.'
    name: $ESCAPED_BRANCH_NAME-b$BUILD_NUMBER
