image: amazoncorretto:17.0.7

variables:
  BRANCH_NAME: $CI_COMMIT_REF_NAME
  BUILD_NUMBER: $CI_PIPELINE_ID

stages:
  - test
  - release

test:
  stage: test
  script:
    - ./gradlew :spring-bootstrap:test -Dfile.encoding=UTF8
  artifacts:
    reports:
      junit: modules/**/build/test-results/test/TEST-*.xml

release:
  stage: release
  when: manual
  script:
    - ESCAPED_BRANCH_NAME="$(echo "$BRANCH_NAME" | sed -e 's|/|_|g')"
    - ./gradlew --stacktrace :spring-bootstrap:buildPlugin :spring-bootstrap:signPlugin -PsnapshotVersion=$BUILD_NUMBER -PdistFilePostfix=$ESCAPED_BRANCH_NAME-b$BUILD_NUMBER -PsetUntilVersion -Pobfuscate
    - ./gradlew --stacktrace :spring-bootstrap:runPluginVerifier
  artifacts:
    paths:
      - modules/spring-bootstrap/build/reports/pluginVerifier
      - modules/spring-bootstrap/build/distributions/*.zip
      - modules/spring-bootstrap/build/distributions/source.map