name: "Explyt Tests: Plugin bug"
description: "Any problem in Explyt Tests plugin and not in generated tests quality"
title: "[BUG] "
labels: test-plugin-bug
assignees: []

body:
  - type: markdown
    attributes:
      value: "Thanks for reporting spring-plugin bug!"

  - type: textarea
    id: details
    attributes:
      label: Problem details
      description: "Describe the problem you faced"
      placeholder: |
        Example:
        - Test class was created outside the package source class is located in
        - Mock framework was not detected in test module
        - Slow operation on EDT error was thrown during test generation

    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "Please provide us as more details on how to reproduce this issue, as you can"
      placeholder: |
        If your project is open-sourced, show the name of your target (class, method, test class), please, and a link on GitHub.
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Additional information"
      description: "Any additional information that can help us to investigate the reported problem"
      placeholder: "Logs, screenshots, etc."
    validations:
      required: false

  - type: textarea
    id: plugin_version
    attributes:
      label: Plugin version
      description: "Type plugin version here"
      placeholder: "Example: 1.2.0"
    validations:
      required: false

  - type: dropdown
    id: build_system
    attributes:
      label: Build system
      description: "Build system where project was built"
      options:
        - Gradle
        - Maven
        - IntelliJ
      default: 0
    validations:
      required: true

  - type: dropdown
    id: llm_provider
    attributes:
      label: LLM provider
      description: "Choose LLM provider"
      options:
        - Open AI (Default)
        - DeepSeek
        - Ollama
        - Another
      default: 0
    validations:
      required: true

  - type: textarea
    id: llm_model
    attributes:
      label: LLM model
      description: "Type LLM model here"
      placeholder: "Default"
    validations:
      required: false

  - type: dropdown
    id: test_framework
    attributes:
      label: Test framework
      description: "Choose test framework"
      options:
        - Not important
        - JUnit 5
        - TestNG
        - JUnit 4
        - Kotlin-test
      default: 0
    validations:
      required: true

  - type: dropdown
    id: mock_framework
    attributes:
      label: Mock framework
      description: "Choose mock framework"
      options:
        - Not important
        - Mockito
        - MockK
      default: 0
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: 'Example: context size, source language, etc.'
      placeholder: "Any other information that can help us"
    validations:
      required: false
