name: test

on:
  push:

env:
  BRANCH_NAME: $GITHUB_REF_NAME
  BUILD_NUMBER: $GITHUB_RUN_ID

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew --stacktrace --info --warning-mode all :spring-bootstrap:test -Dfile.encoding=UTF8
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'modules/**/build/test-results/test/TEST-*.xml'


